### ISSUE TITLE
Display name of package or `informant read` command

### ISSUE THREAD

**Issue by GameKyuubi** [bradford-smith94/informant#20]
I like this package, but I find every time it prevents me from upgrading (as intended) I forget the name of the package so I can't do `informant read`!  If it reminded the user of the command when it prevents an upgrade that would be lovely.

**Comment by codeclem** [comment]
When the pre-transaction hook fails and aborts the upgrade the news message is printed and marked as read at the same time, so you can just rerun the upgrade command and it should go through.

**Comment by bradford-smith94** [comment]
To provide more detail: 
- When there is only 1 unread news item the pacman hook will abort the upgrade and print the news item. I chose this behavior so that the user is forced/has time to read the new item. Since it's already been printed just running the upgrade command again will succeed.
- When there is more than 1 news item the pacman hook will abort the upgrade with a message of the form "There are # unread news items! Use informant to read them." In this case I thought printing all the missed items automatically could quickly clutter the screen so using informant before re-running the upgrade is required.

With that said, if there are suggestions to make the user experience better (maybe making this behavior more clear in the README/documentation or updating the messages that get printed) I'm open to it.

**Comment by bradford-smith94** [comment]
@GameKyuubi v0.3.0 updated a lot of messages, specifically there is: [this one](https://github.com/bradford-smith94/informant/blob/master/informant#L241) to remind the user for the case you mentioned. Is this enough to consider this issue closed?

**Comment by GameKyuubi** [comment]
Absolutely.  Nice work!
